# Example file for a single square cell in 2D
1 4 4 	       	   # NumCell NumWall NumVertex 
0 0 -1 0 1	   # connections: edge_label cell1 cell2 vertex1 vertex2
1 0 -1 0 2
2 0 -1 1 3
3 0 -1 2 3

4 2		   # NumVertex Dimension
0.0 0.0 	   # Positions of vertices
1.0 0.0 
0.0 1.0 
1.0 1.0

4 1 4		   # NumEdge NumLength NumVariable
1.0 0.0 0.0 0 0	   # RestLength variable1 .. vN
1.0 0.0	0.0 0 0
1.0 0.0	0.0 0 0
1.0 0.0	0.0 0 0

1 9		   # NumCell NumVariable
0.0 10.0 10.0 10.0 0.0 0 10.0 5.0 2.0 #variable0 .. vN
 