#!/usr/bin/env python3
"""Regenerate tools/port/STATUS.md from the sources.

Reads every reaction name the legacy factory registers (legacy/baseReaction.cc)
and every name this rewrite registers (TISSUE_REGISTER_* macros), and reports
what is outstanding, grouped by the legacy source file that implements it.

A class counts as ported only when *every* name the legacy factory maps to it
resolves here, so an alias left behind still shows up as outstanding.

Usage: python3 tools/port/inventory.py [--check]

  --check  exit non-zero if STATUS.md is out of date, for CI
"""
import collections
import glob
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
STATUS = os.path.join(ROOT, "tools", "port", "STATUS.md")


def legacy_classes():
    """{class name: [registered names]} from the legacy factory."""
    src = open(os.path.join(ROOT, "legacy", "baseReaction.cc"), errors="ignore").read()
    out = collections.defaultdict(list)
    # Each branch is "else if (<conditions>) return new Class(...)". Take every
    # name tested since the previous `new`, so the aliases of a chained
    # condition (`a == "X" || a == "Y"`) all attach to the same class - reading
    # one name per `new` silently lets a class count as ported with its other
    # aliases still missing.
    pos = 0
    for m in re.finditer(r"new\s+([A-Za-z0-9_:]+)\s*\(", src):
        names = re.findall(r'idValue\s*==\s*"([^"]+)"', src[pos:m.start()])
        if names:
            out[m.group(1)] += names
        pos = m.end()
    return out


def ported_names():
    """Every name registered by this rewrite, aliases included."""
    names = set()
    for pat in ("src/tissue/reactions/*.cpp", "src/tissue/compartment/*.cpp"):
        for f in glob.glob(os.path.join(ROOT, pat)):
            src = open(f).read()
            for m in re.finditer(r"TISSUE_REGISTER_\w+\s*\((.*?)\)", src, re.S):
                names |= set(re.findall(r'"([^"]+)"', m.group(1)))
    return names


def locate(classes):
    """Which legacy source implements each class."""
    files = {}
    for pat in ("legacy/*.cc", "legacy/*.h"):
        for f in glob.glob(os.path.join(ROOT, pat)):
            files[f] = open(f, errors="ignore").read()
    loc = {}
    for cls in classes:
        leaf = cls.split("::")[-1]
        for pattern in (rf"\b{re.escape(leaf)}::{re.escape(leaf)}\s*\(",
                        rf"\bclass\s+{re.escape(leaf)}\b"):
            hit = next((os.path.basename(f) for f, s in files.items()
                        if re.search(pattern, s)), None)
            if hit:
                loc[cls] = hit.replace(".h", ".cc")
                break
    return loc


def render():
    classes, done = legacy_classes(), ported_names()
    loc = locate(classes)
    todo = collections.defaultdict(list)
    for cls, names in classes.items():
        if not all(n in done for n in names):
            todo[loc.get(cls, "unresolved")].append((cls, sorted(names)))
    total = sum(len(v) for v in todo.values())

    out = ["# Reaction port status", "",
           "Generated by `tools/port/inventory.py` — do not edit by hand.", "",
           "The rewrite is a fork of the original Tissue; `legacy/` holds the",
           "original sources and is the reference for this port. A class counts as",
           "ported only when every name the legacy factory registers for it resolves",
           "here, so a missing alias still shows as outstanding.", "",
           f"**{len(done)} names registered here; {total} classes outstanding.**",
           "Every reaction used by the shipped tutorials is ported, so `examples/`",
           "all run.", "",
           "Method and the log of validated batches are in `NOTES.md`.", "",
           "| legacy source | outstanding |", "|---|---|"]
    order = sorted(todo.items(), key=lambda kv: (-len(kv[1]), kv[0]))
    for f, cs in order:
        out.append(f"| `legacy/{f}` | {len(cs)} |")
    out += ["", "## Outstanding, by source", ""]
    for f, cs in order:
        out += [f"### `legacy/{f}` ({len(cs)})", ""]
        for cls, names in sorted(cs):
            alias = ", ".join(f"`{n}`" for n in names)
            out.append(f"- `{cls}` — {alias}")
        out.append("")
    return "\n".join(out) + "\n", total


if __name__ == "__main__":
    text, total = render()
    if "--check" in sys.argv:
        cur = open(STATUS).read() if os.path.exists(STATUS) else ""
        if cur != text:
            print("STATUS.md is out of date; run tools/port/inventory.py")
            sys.exit(1)
        print(f"STATUS.md current: {total} classes outstanding")
    else:
        open(STATUS, "w").write(text)
        print(f"wrote {os.path.relpath(STATUS, ROOT)}: {total} classes outstanding")
