//
// Filename     : growthForce.h
// Description  : Classes describing growth updates by applying forces on vertices
// Author(s)    : Henrik Jonsson (henrik.jonsson@slcu.cam.ac.uk)
// Created      : April 2018
// Revision     : $Id:$
//
#ifndef GROWTHFORCE_H
#define GROWTHFORCE_H

#include <cmath>
#include "baseReaction.h"
#include "tissue.h"

///
/// @brief This namespace includes reactions to generate the forces to grow into different shapes
///
/// @details Growth in general thought to require forces, in plants generated by cellular turgor
/// pressure. An example is a radial force acting on all vertices generating an isotropic growth.
/// This namespace collects reactions to generate forces on vertices to approximate such forces
/// or more abtractly to generate specific shapes (e.g. by generating forces moving vertices on on asurface
/// of a specific shape). These reactions are typically then combine with mechanical reactions to generate elasticity
/// and element growth reactions to generate irreversible growth.
///
/// @see namespace Force Some resembling reactions, but where typically the force is 'external' or only acting on 
/// a subset of vertices.
/// @see namespace WallGrowth Collection of reactions to generate irreversible growth
///
namespace GrowthForce {
  ///
  /// @brief Growth via vertex forces radially outwards
  ///
  /// @details The tissue grows from vertex movement radially outwards. The update is given by
  /// @f[ \frac{dr}{dt} = p_{0} @f] (if @f$ p_1=0 @f$) or
  /// @f[ \frac{dr}{dt} = p_{0} r @f] (if @f$ p_{1}=1 @f$)
  /// where @f$ p_{0} @f$ is the force/rate (@f$ k_{growth} @f$),
  /// @f$ p_{1} @f$ {0,1} is a flag determining which function to be used (@f$ r_{pow} @f$).
  /// In a model file the reaction is defined as
  /// @verbatim
  /// GrowthForce::Radial 2 0
  /// p_0 p_1
  /// @endverbatim
  ///
  /// @note Used to be named MoveVertexRadially (still allowed)
  ///
  class Radial : public BaseReaction {
  public:
    ///
    /// @brief Main constructor
    ///
    /// @details This is the main constructor which sets the parameters and variable
    /// indices that defines the reaction.
    ///
    /// @param paraValue vector with parameters
    ///
    /// @param indValue vector of vectors with variable indices
    ///
    /// @see BaseReaction::createReaction(std::vector<double> &paraValue,...)
    ///
    Radial(std::vector<double> &paraValue,
	   std::vector< std::vector<size_t> >
	   &indValue );
    ///
    /// @brief Derivative function for this reaction class
    ///
    /// @see BaseReaction::derivs(Tissue &T,...)
    ///
    void derivs(Tissue &T,
                DataMatrix &cellData,
                DataMatrix &wallData,
                DataMatrix &vertexData,
                DataMatrix &cellDerivs,
                DataMatrix &wallDerivs,
                DataMatrix &vertexDerivs );
    
    ///
    /// @brief For this function it just returns the derivs (i.e. no noise added)
    ///
    /// @see BaseReaction::derivsWithAbs(Tissue &T,...)
    ///
    void derivsWithAbs(Tissue &T,
		       DataMatrix &cellData,
		       DataMatrix &wallData,
		       DataMatrix &vertexData,
		       DataMatrix &cellDerivs,
		       DataMatrix &wallDerivs,
		       DataMatrix &vertexDerivs,
		       DataMatrix &sdydtCell,
		       DataMatrix &sdydtWall,
		       DataMatrix &sdydtVertex );
  };

  namespace CenterTriangulation {
    ///
    /// @brief Growth via a force acting on vertices radially outwards
    ///
    ///  The tissue grows from vertex movement radially outwards,  and also
    /// includes moving the vertex defining the 'center' of the cells in the
    /// center triangulated mesh. The update is given by
    /// @f[ \frac{dr}{dt} = p_{0} @f] (if @f$ p_1=0 @f$) or
    /// @f[ \frac{dr}{dt} = p_{0} r @f] (if @f$ p_{1}=1 @f$)
    ///
    /// @f$ p_{0} @f$ is the rate (@f$ k_{growth} @f$),
    /// @f$ p_{1} @f$ {0,1} is a flag determining which function to be used (@f$ r_{pow} @f$).
    /// In a model file the reaction is defined as
    /// @verbatim
    /// GrowthForce::CenterTriangulation::Radial 2 1 1
    /// p_0 p_1
    /// InternalVarStartIndex
    /// @endverbatim
    /// @see Force::Radial (same but without moving the central vertices)
    /// @note Used to be named MoveVertexRadiallycenterTriangulation (still allowed).
    ///
    class Radial : public BaseReaction {
      
    public:
      ///
      /// @brief Main constructor
      ///
      /// This is the main constructor which sets the parameters and variable
      /// indices that defines the reaction.
      ///
      /// @param paraValue vector with parameters
      ///
      /// @param indValue vector of vectors with variable indices
      ///
      /// @see BaseReaction::createReaction(std::vector<double> &paraValue,...)
      ///
      Radial(std::vector<double> &paraValue,
	     std::vector< std::vector<size_t> >
	     &indValue );
      ///
      /// @brief Derivative function for this reaction class
      ///
      /// @see BaseReaction::derivs(Tissue &T,...)
      ///
      void derivs(Tissue &T,
		  DataMatrix &cellData,
		  DataMatrix &wallData,
		  DataMatrix &vertexData,
		  DataMatrix &cellDerivs,
		  DataMatrix &wallDerivs,
		  DataMatrix &vertexDerivs );
    };
  } // end namespace CenterTriangulation
} // end namespace GrowthForce

#endif
